### ISSUE TITLE
New release of 1.5.6?

### ISSUE THREAD

**Issue by skoczen** [peterbe/django-static#40]
Hey there,

Just wondering if you'd be up to push a new release that includes the `DJANGO_STATIC_FILENAME_GENERATOR` functionality.  I'm building a package that depends on django-static, and it'd be great to be able to reference a pypi version, instead of a github branch.

Thanks - and thanks for this excellent library!

-Steven

**Comment by peterbe** [comment]
Sure thing!

**Comment by peterbe** [comment]
Done https://pypi.python.org/pypi/django-static

**Comment by skoczen** [comment]
@peterbe Fantastic - thanks for the quick turnaround!
